apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deployment
  labels:
    app: mywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp
          image: aksvmregistry.azurecr.io/azurewebapp
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-loadbalancer-service
  labels:
    app: mywebapp
spec:
  type: LoadBalancer
  selector:
    app: mywebapp
  ports:
    - port: 80
      targetPort: 80